/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@o-rango/orango-demo-tools';


import {
  MdcButtonComponent as OMdcButton
} from './components/o-mdc-button/o-mdc-button';

declare global {
  interface HTMLOMdcButtonElement extends OMdcButton, HTMLElement {
  }
  var HTMLOMdcButtonElement: {
    prototype: HTMLOMdcButtonElement;
    new (): HTMLOMdcButtonElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-button": HTMLOMdcButtonElement;
  }
  interface ElementTagNameMap {
    "o-mdc-button": HTMLOMdcButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-button": JSXElements.OMdcButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcButtonAttributes extends HTMLAttributes {
      compact?: boolean;
      dense?: boolean;
      disabled?: boolean;
      href?: string;
      id?: string;
      name?: string;
      raised?: boolean;
      stroked?: boolean;
      unelevated?: boolean;
    }
  }
}


import {
  MdcCheckboxComponent as OMdcCheckbox
} from './components/o-mdc-checkbox/o-mdc-checkbox';

declare global {
  interface HTMLOMdcCheckboxElement extends OMdcCheckbox, HTMLElement {
  }
  var HTMLOMdcCheckboxElement: {
    prototype: HTMLOMdcCheckboxElement;
    new (): HTMLOMdcCheckboxElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-checkbox": HTMLOMdcCheckboxElement;
  }
  interface ElementTagNameMap {
    "o-mdc-checkbox": HTMLOMdcCheckboxElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-checkbox": JSXElements.OMdcCheckboxAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcCheckboxAttributes extends HTMLAttributes {
      alignEnd?: boolean;
      checked?: boolean;
      disabled?: boolean;
      id?: string;
      indeterminate?: boolean;
      label?: string;
      name?: string;
      value?: string;
    }
  }
}


import {
  MdcFabComponent as OMdcFab
} from './components/o-mdc-fab/o-mdc-fab';

declare global {
  interface HTMLOMdcFabElement extends OMdcFab, HTMLElement {
  }
  var HTMLOMdcFabElement: {
    prototype: HTMLOMdcFabElement;
    new (): HTMLOMdcFabElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-fab": HTMLOMdcFabElement;
  }
  interface ElementTagNameMap {
    "o-mdc-fab": HTMLOMdcFabElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-fab": JSXElements.OMdcFabAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcFabAttributes extends HTMLAttributes {
      absolute?: boolean;
      fixed?: boolean;
      href?: string;
      id?: string;
      mini?: boolean;
      name?: string;
    }
  }
}


import {
  MdcFormFieldComponent as OMdcFormField
} from './components/o-mdc-form-field/o-mdc-form-field';

declare global {
  interface HTMLOMdcFormFieldElement extends OMdcFormField, HTMLElement {
  }
  var HTMLOMdcFormFieldElement: {
    prototype: HTMLOMdcFormFieldElement;
    new (): HTMLOMdcFormFieldElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-form-field": HTMLOMdcFormFieldElement;
  }
  interface ElementTagNameMap {
    "o-mdc-form-field": HTMLOMdcFormFieldElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-form-field": JSXElements.OMdcFormFieldAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcFormFieldAttributes extends HTMLAttributes {
      alignEnd?: boolean;
      label?: string;
    }
  }
}


import {
  MdcLinearProgressComponent as OMdcLinearProgress
} from './components/o-mdc-linear-progress/o-mdc-linear-progress';

declare global {
  interface HTMLOMdcLinearProgressElement extends OMdcLinearProgress, HTMLElement {
  }
  var HTMLOMdcLinearProgressElement: {
    prototype: HTMLOMdcLinearProgressElement;
    new (): HTMLOMdcLinearProgressElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-linear-progress": HTMLOMdcLinearProgressElement;
  }
  interface ElementTagNameMap {
    "o-mdc-linear-progress": HTMLOMdcLinearProgressElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-linear-progress": JSXElements.OMdcLinearProgressAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcLinearProgressAttributes extends HTMLAttributes {
      accent?: boolean;
      buffer?: number;
      id?: string;
      indeterminate?: boolean;
      open?: boolean;
      progress?: number;
      reverse?: boolean;
    }
  }
}


import {
  MdcRadioComponent as OMdcRadio
} from './components/o-mdc-radio/o-mdc-radio';

declare global {
  interface HTMLOMdcRadioElement extends OMdcRadio, HTMLElement {
  }
  var HTMLOMdcRadioElement: {
    prototype: HTMLOMdcRadioElement;
    new (): HTMLOMdcRadioElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-radio": HTMLOMdcRadioElement;
  }
  interface ElementTagNameMap {
    "o-mdc-radio": HTMLOMdcRadioElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-radio": JSXElements.OMdcRadioAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcRadioAttributes extends HTMLAttributes {
      alignEnd?: boolean;
      checked?: boolean;
      disabled?: boolean;
      id?: string;
      label?: string;
      name?: string;
      value?: string;
    }
  }
}


import {
  MdcSelectComponent as OMdcSelect
} from './components/o-mdc-select/o-mdc-select';

declare global {
  interface HTMLOMdcSelectElement extends OMdcSelect, HTMLElement {
  }
  var HTMLOMdcSelectElement: {
    prototype: HTMLOMdcSelectElement;
    new (): HTMLOMdcSelectElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-select": HTMLOMdcSelectElement;
  }
  interface ElementTagNameMap {
    "o-mdc-select": HTMLOMdcSelectElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-select": JSXElements.OMdcSelectAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcSelectAttributes extends HTMLAttributes {
      selectedTextContent?: any;
      tabIndex?: number;
    }
  }
}


import {
  MdcSnackbarComponent as OMdcSnackbar
} from './components/o-mdc-snackbar/o-mdc-snackbar';

declare global {
  interface HTMLOMdcSnackbarElement extends OMdcSnackbar, HTMLElement {
  }
  var HTMLOMdcSnackbarElement: {
    prototype: HTMLOMdcSnackbarElement;
    new (): HTMLOMdcSnackbarElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-snackbar": HTMLOMdcSnackbarElement;
  }
  interface ElementTagNameMap {
    "o-mdc-snackbar": HTMLOMdcSnackbarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-snackbar": JSXElements.OMdcSnackbarAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcSnackbarAttributes extends HTMLAttributes {
      actionOnBottom?: boolean;
      alignStart?: boolean;
      dismissesOnAction?: boolean;
    }
  }
}


import {
  MdcTextFieldComponent as OMdcTextField
} from './components/o-mdc-text-field/o-mdc-text-field';

declare global {
  interface HTMLOMdcTextFieldElement extends OMdcTextField, HTMLElement {
  }
  var HTMLOMdcTextFieldElement: {
    prototype: HTMLOMdcTextFieldElement;
    new (): HTMLOMdcTextFieldElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-text-field": HTMLOMdcTextFieldElement;
  }
  interface ElementTagNameMap {
    "o-mdc-text-field": HTMLOMdcTextFieldElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-text-field": JSXElements.OMdcTextFieldAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcTextFieldAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MdcThemeComponent as OMdcTheme
} from './components/o-mdc-theme/o-mdc-theme';

declare global {
  interface HTMLOMdcThemeElement extends OMdcTheme, HTMLElement {
  }
  var HTMLOMdcThemeElement: {
    prototype: HTMLOMdcThemeElement;
    new (): HTMLOMdcThemeElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-theme": HTMLOMdcThemeElement;
  }
  interface ElementTagNameMap {
    "o-mdc-theme": HTMLOMdcThemeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-theme": JSXElements.OMdcThemeAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcThemeAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MdcToolbarRowComponent as OMdcToolbarRow
} from './components/o-mdc-toolbar/o-mdc-toolbar-row';

declare global {
  interface HTMLOMdcToolbarRowElement extends OMdcToolbarRow, HTMLElement {
  }
  var HTMLOMdcToolbarRowElement: {
    prototype: HTMLOMdcToolbarRowElement;
    new (): HTMLOMdcToolbarRowElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-toolbar-row": HTMLOMdcToolbarRowElement;
  }
  interface ElementTagNameMap {
    "o-mdc-toolbar-row": HTMLOMdcToolbarRowElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-toolbar-row": JSXElements.OMdcToolbarRowAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcToolbarRowAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MdcToolbarSectionComponent as OMdcToolbarSection
} from './components/o-mdc-toolbar/o-mdc-toolbar-section';

declare global {
  interface HTMLOMdcToolbarSectionElement extends OMdcToolbarSection, HTMLElement {
  }
  var HTMLOMdcToolbarSectionElement: {
    prototype: HTMLOMdcToolbarSectionElement;
    new (): HTMLOMdcToolbarSectionElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-toolbar-section": HTMLOMdcToolbarSectionElement;
  }
  interface ElementTagNameMap {
    "o-mdc-toolbar-section": HTMLOMdcToolbarSectionElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-toolbar-section": JSXElements.OMdcToolbarSectionAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcToolbarSectionAttributes extends HTMLAttributes {
      alignEnd?: boolean;
      alignStart?: boolean;
      shrinkToFit?: boolean;
    }
  }
}


import {
  MdcToolbarTitleComponent as OMdcToolbarTitle
} from './components/o-mdc-toolbar/o-mdc-toolbar-title';

declare global {
  interface HTMLOMdcToolbarTitleElement extends OMdcToolbarTitle, HTMLElement {
  }
  var HTMLOMdcToolbarTitleElement: {
    prototype: HTMLOMdcToolbarTitleElement;
    new (): HTMLOMdcToolbarTitleElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-toolbar-title": HTMLOMdcToolbarTitleElement;
  }
  interface ElementTagNameMap {
    "o-mdc-toolbar-title": HTMLOMdcToolbarTitleElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-toolbar-title": JSXElements.OMdcToolbarTitleAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcToolbarTitleAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MdcToolbarComponent as OMdcToolbar
} from './components/o-mdc-toolbar/o-mdc-toolbar';

declare global {
  interface HTMLOMdcToolbarElement extends OMdcToolbar, HTMLElement {
  }
  var HTMLOMdcToolbarElement: {
    prototype: HTMLOMdcToolbarElement;
    new (): HTMLOMdcToolbarElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-toolbar": HTMLOMdcToolbarElement;
  }
  interface ElementTagNameMap {
    "o-mdc-toolbar": HTMLOMdcToolbarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-toolbar": JSXElements.OMdcToolbarAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcToolbarAttributes extends HTMLAttributes {
      fixed?: boolean;
      fixedLastrow?: boolean;
      flexible?: boolean;
      flexibleDefault?: boolean;
      id?: string;
      name?: string;
      waterfall?: boolean;
    }
  }
}

