/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  MdcToolbarRowComponent as OMdcToolbarRow
} from './components/o-mdc-toolbar/o-mdc-toolbar-row';

declare global {
  interface HTMLOMdcToolbarRowElement extends OMdcToolbarRow, HTMLElement {
  }
  var HTMLOMdcToolbarRowElement: {
    prototype: HTMLOMdcToolbarRowElement;
    new (): HTMLOMdcToolbarRowElement;
  };
  interface HTMLElementTagNameMap {
    "o-mdc-toolbar-row": HTMLOMdcToolbarRowElement;
  }
  interface ElementTagNameMap {
    "o-mdc-toolbar-row": HTMLOMdcToolbarRowElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-mdc-toolbar-row": JSXElements.OMdcToolbarRowAttributes;
    }
  }
  namespace JSXElements {
    export interface OMdcToolbarRowAttributes extends HTMLAttributes {
      
    }
  }
}

